# Generated by Django 5.2.11 on 2026-03-23 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_recruiterprofile_company_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(default='HR Manager', max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_members', to='accounts.recruiterprofile')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'email')},
            },
        ),
    ]
