# Generated by Django 5.2.11 on 2026-03-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='experience_summary',
            field=models.TextField(blank=True, help_text='Brief work experience summary'),
        ),
        migrations.AddField(
            model_name='application',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='application_resumes/'),
        ),
        migrations.AddField(
            model_name='application',
            name='skills_summary',
            field=models.TextField(blank=True, help_text='Comma-separated skills'),
        ),
    ]
