# Generated by Django 5.2.11 on 2026-03-16 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('duration_mins', models.PositiveSmallIntegerField(default=60, help_text='Duration in minutes')),
                ('interview_type', models.CharField(choices=[('video', 'Video Call'), ('phone', 'Phone Call'), ('onsite', 'On-site')], default='video', max_length=10)),
                ('location', models.CharField(blank=True, help_text='Physical address (for on-site) or platform name (for video/phone)', max_length=300)),
                ('meeting_link', models.URLField(blank=True, help_text='Zoom / Google Meet / Teams link')),
                ('notes', models.TextField(blank=True, help_text='Message to the candidate — preparation tips, what to bring, etc.')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='applications.application')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
    ]
