# Generated by Django 5.2.11 on 2026-04-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Street address, city, state, postal code, country'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='languages',
            field=models.CharField(blank=True, help_text='Comma-separated languages, e.g. English, Hindi, French', max_length=300),
        ),
    ]
