# Generated by Django 5.2.11 on 2026-03-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-10', '1–10 employees'), ('11-50', '11–50 employees'), ('51-200', '51–200 employees'), ('201-500', '201–500 employees'), ('501-1000', '501–1,000 employees'), ('1001-5000', '1,001–5,000 employees'), ('5000+', '5,000+ employees')], max_length=20),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_type',
            field=models.CharField(blank=True, choices=[('private', 'Private Company'), ('public', 'Public Company'), ('startup', 'Startup'), ('nonprofit', 'Non-profit'), ('government', 'Government'), ('freelance', 'Freelance / Agency')], max_length=20),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='founded_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='industry',
            field=models.CharField(blank=True, choices=[('technology', 'Technology & Software'), ('finance', 'Finance & Banking'), ('healthcare', 'Healthcare & Medical'), ('education', 'Education & Training'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail & E-commerce'), ('consulting', 'Consulting & Professional Services'), ('media', 'Media & Entertainment'), ('real_estate', 'Real Estate & Construction'), ('logistics', 'Logistics & Supply Chain'), ('energy', 'Energy & Utilities'), ('government', 'Government & Public Sector'), ('nonprofit', 'Non-profit & NGO'), ('hospitality', 'Hospitality & Tourism'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
