# Generated by Django 5.2.11 on 2026-03-12 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_recruiterprofile_company_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_remote', models.BooleanField(default=False)),
                ('required_skills', models.TextField(blank=True, help_text='Comma-separated list of required skills')),
                ('experience_level', models.CharField(choices=[('any', 'Any experience level'), ('entry', 'Entry Level (0–2 years)'), ('mid', 'Mid Level (2–5 years)'), ('senior', 'Senior Level (5–10 years)'), ('lead', 'Lead / Principal (10+ years)')], default='any', max_length=10)),
                ('experience_years_min', models.PositiveSmallIntegerField(default=0)),
                ('experience_years_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('education_required', models.CharField(choices=[('any', 'Any'), ('high_school', 'High School Diploma'), ('diploma', 'Diploma / Certificate'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'Ph.D / Doctorate')], default='any', max_length=20)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=3)),
                ('salary_period', models.CharField(choices=[('monthly', 'Per Month'), ('yearly', 'Per Year')], default='yearly', max_length=10)),
                ('is_salary_visible', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.recruiterprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
