# Generated by Django 5.2.11 on 2026-04-05 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('experience', 'Work Experience'), ('certificate', 'Certificate'), ('criminal', 'Criminal Record')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='submission_docs/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assessments.assessmentattempt')),
            ],
            options={
                'ordering': ['document_type', 'submitted_at'],
            },
        ),
    ]
