# Generated by Django 5.2.11 on 2026-04-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_documentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='doc_requested',
            field=models.BooleanField(default=False, help_text='Recruiter has requested document verification from this candidate'),
        ),
    ]
