# Generated by Django 5.2.11 on 2026-03-12 04:46

import django.db.models.deletion
import resume.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=resume.models.resume_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('file_size', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('parse_error', models.TextField(blank=True)),
                ('raw_text', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_name', models.CharField(blank=True, max_length=150)),
                ('extracted_email', models.EmailField(blank=True, max_length=254)),
                ('extracted_phone', models.CharField(blank=True, max_length=40)),
                ('extracted_linkedin', models.URLField(blank=True)),
                ('extracted_github', models.URLField(blank=True)),
                ('extracted_website', models.URLField(blank=True)),
                ('summary_text', models.TextField(blank=True)),
                ('skills_text', models.TextField(blank=True)),
                ('education_text', models.TextField(blank=True)),
                ('experience_text', models.TextField(blank=True)),
                ('certifications_text', models.TextField(blank=True)),
                ('projects_text', models.TextField(blank=True)),
                ('extracted_skills', models.JSONField(default=list)),
                ('extracted_keywords', models.JSONField(default=list)),
                ('estimated_experience_years', models.FloatField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('phd', 'Ph.D / Doctorate'), ('master', "Master's Degree"), ('bachelor', "Bachelor's Degree"), ('associate', 'Associate Degree'), ('diploma', 'Diploma / Certificate'), ('high_school', 'High School'), ('', 'Not detected')], max_length=20)),
                ('total_words', models.PositiveIntegerField(default=0)),
                ('total_keywords', models.PositiveIntegerField(default=0)),
                ('tech_skill_count', models.PositiveIntegerField(default=0)),
                ('soft_skill_count', models.PositiveIntegerField(default=0)),
                ('parsed_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed', to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=120)),
                ('frequency', models.PositiveIntegerField(default=1)),
                ('is_skill', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('tech', 'Technical'), ('soft', 'Soft Skill'), ('other', 'Other')], default='other', max_length=10)),
                ('parsed_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='resume.parsedresume')),
            ],
            options={
                'ordering': ['-frequency'],
                'unique_together': {('parsed_resume', 'word')},
            },
        ),
    ]
