# Generated by Django 5.2.11 on 2026-03-24 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuiltResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "Software Developer Resume"', max_length=200)),
                ('template_name', models.CharField(choices=[('classic', 'Classic Professional'), ('modern', 'Modern Clean'), ('sidebar', 'Executive Sidebar')], default='classic', max_length=20)),
                ('custom_name', models.CharField(blank=True, max_length=200)),
                ('custom_email', models.EmailField(blank=True, max_length=254)),
                ('custom_phone', models.CharField(blank=True, max_length=30)),
                ('custom_location', models.CharField(blank=True, max_length=150)),
                ('custom_linkedin', models.URLField(blank=True)),
                ('custom_website', models.URLField(blank=True)),
                ('summary', models.TextField(blank=True, help_text='A 3-5 sentence professional summary tailored for this resume.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='built_resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
