# Generated by Django 5.2.11 on 2026-03-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_add_built_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='builtresume',
            name='accent_color',
            field=models.CharField(blank=True, default='', help_text='Hex colour e.g. #4f46e5 — leave blank for template default', max_length=7),
        ),
        migrations.AddField(
            model_name='builtresume',
            name='font_family',
            field=models.CharField(choices=[('sans', 'Modern Sans'), ('inter', 'Inter'), ('serif', 'Classic Serif'), ('montserrat', 'Montserrat'), ('raleway', 'Raleway')], default='sans', max_length=20),
        ),
        migrations.AddField(
            model_name='builtresume',
            name='section_order',
            field=models.CharField(blank=True, default='summary,experience,skills,education,certs', help_text='Comma-separated section keys controlling display order', max_length=120),
        ),
    ]
