# Generated by Django 5.2.11 on 2026-03-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_customization'),
    ]

    operations = [
        migrations.AddField(
            model_name='builtresume',
            name='personal_details',
            field=models.TextField(blank=True, help_text='Optional extra info: GitHub, awards, languages, references, etc.'),
        ),
        migrations.AlterField(
            model_name='builtresume',
            name='template_name',
            field=models.CharField(choices=[('classic', 'Classic Professional'), ('modern', 'Modern Clean'), ('sidebar', 'Executive Sidebar'), ('minimal', 'ATS Minimal'), ('techdev', 'Tech & Developer')], default='classic', max_length=20),
        ),
    ]
