# Generated by Django 5.2.11 on 2026-03-12 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_score', models.FloatField(default=0)),
                ('experience_score', models.FloatField(default=0)),
                ('education_score', models.FloatField(default=0)),
                ('keywords_score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('matched_keywords', models.JSONField(default=list)),
                ('experience_years_found', models.FloatField(default=0)),
                ('education_rank_found', models.PositiveSmallIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='jobs.jobpost')),
            ],
            options={
                'ordering': ['-total_score'],
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
