# Generated by Django 5.2.11 on 2026-03-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchscore',
            name='recruiter_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='matchscore',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
